//package others;
//
///*
// * To change this template, choose Tools | Templates
// * and open the template in the editor.
// */
///**
// *
// * @author Benoit Meilhac <B.Meilhac@westminster.ac.uk>
// */
//public class LoadJSDL {
//
//    public static String returnPortalData() {
//        return "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n"
//                + "<JobDefinition xmlns=\"http://schemas.ggf.org/jsdl/2005/11/jsdl\" xmlns:ns2=\"http://schemas.ggf.org/jsdl/2005/11/jsdl-posix\" xmlns:ns3=\"uri:MBSchedulingDescriptionLanguage\" xmlns:ns4=\"extension.dci\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://schemas.ggf.org/jsdl/2005/11/jsdl\">\n"
//                + "    <JobDescription>\n"
//                + "        <JobIdentification>\n"
//                + "            <JobName>TestTaverna2v1#1.0:</JobName>\n"
//                + "            <JobAnnotation>fd84cdf6-15af-456a-aa61-d496842ca1ed</JobAnnotation>\n"
//                + "        </JobIdentification>\n"
//                + "        <Application clientip=\"192.168.152.5\">\n"
//                + "            <ApplicationName>guse://10532510229060643zentest-Job0/0</ApplicationName>\n"
//                + "            <ns2:POSIXApplication_Type xmlns:ns4=\"uri:MBSchedulingDescriptionLanguage\" xmlns:ns3=\"extension.dci\" xmlns:ns5=\"http://cloud.extension.jsdl\">\n"
//                + "                <ns2:Argument>Roger</ns2:Argument>\n"
//                + "                <ns2:Argument>greeting</ns2:Argument>\n"
//                + "                <ns2:Output>stdout.log</ns2:Output>\n"
//                + "                <ns2:Error>stderr.log</ns2:Error>\n"
//                + "                <ns2:UserName>10196</ns2:UserName>\n"
//                + "                <ns2:GroupName>http://192.168.152.5:8080/wspgrade</ns2:GroupName>\n"
//                + "            </ns2:POSIXApplication_Type>\n"
//                + "        </Application>\n"
//                + "        <Resources>\n"
//                + "            <CandidateHosts>\n"
//                + "                <HostName>TestTaverna2v1#1.0:/PreDeployWestFocus</HostName>\n"
//                + "            </CandidateHosts>\n"
//                + "            <OperatingSystem>\n"
//                + "                <OperatingSystemType>\n"
//                + "                    <OperatingSystemName>LINUX</OperatingSystemName>\n"
//                + "                </OperatingSystemType>\n"
//                + "            </OperatingSystem>\n"
//                + "        </Resources>\n"
//                + "        <DataStaging name=\"PORT0\">\n"
//                + "            <FileName>greeting</FileName>\n"
//                + "            <FilesystemName>dcibridge.outputs.zip</FilesystemName>\n"
//                + "            <CreationFlag>overwrite</CreationFlag>\n"
//                + "            <DeleteOnTermination>true</DeleteOnTermination>\n"
//                + "            <Target>\n"
//                + "                <URI>http://192.168.152.5:8080/storage/FileUploadServlet?path=http:__192.168.152.5:8080_wspgrade/10196/gemlca-1outt/Job0/outputs/10532510229060643zentest/0/&amp;link=PORT0</URI>\n"
//                + "            </Target>\n"
//                + "        </DataStaging>\n"
//                + "        <DataStaging>\n"
//                + "            <FileName>stderr.log</FileName>\n"
//                + "            <FilesystemName>dcibridge.outputs.zip</FilesystemName>\n"
//                + "            <CreationFlag>overwrite</CreationFlag>\n"
//                + "            <DeleteOnTermination>true</DeleteOnTermination>\n"
//                + "            <Target>\n"
//                + "                <URI>http://192.168.152.5:8080/storage/FileUploadServlet?path=http:__192.168.152.5:8080_wspgrade/10196/gemlca-1outt/Job0/outputs/10532510229060643zentest/0</URI>\n"
//                + "            </Target>\n"
//                + "        </DataStaging>\n"
//                + "        <DataStaging>\n"
//                + "            <FileName>stdout.log</FileName>\n"
//                + "            <FilesystemName>dcibridge.outputs.zip</FilesystemName>\n"
//                + "            <CreationFlag>overwrite</CreationFlag>\n"
//                + "            <DeleteOnTermination>true</DeleteOnTermination>\n"
//                + "            <Target>\n"
//                + "                <URI>http://192.168.152.5:8080/storage/FileUploadServlet?path=http:__192.168.152.5:8080_wspgrade/10196/gemlca-1outt/Job0/outputs/10532510229060643zentest/0</URI>\n"
//                + "            </Target>\n"
//                + "        </DataStaging>\n"
//                + "        <DataStaging>\n"
//                + "            <FileName>gridnfo.log</FileName>\n"
//                + "            <FilesystemName>dcibridge.outputs.zip</FilesystemName>\n"
//                + "            <CreationFlag>overwrite</CreationFlag>\n"
//                + "            <DeleteOnTermination>true</DeleteOnTermination>\n"
//                + "            <Target>\n"
//                + "                <URI>http://192.168.152.5:8080/storage/FileUploadServlet?path=http:__192.168.152.5:8080_wspgrade/10196/gemlca-1outt/Job0/outputs/10532510229060643zentest/0</URI>\n"
//                + "            </Target>\n"
//                + "        </DataStaging>\n"
//                + "        <DataStaging>\n"
//                + "            <FileName>guse.jsdl</FileName>\n"
//                + "            <FilesystemName>dcibridge.outputs.zip</FilesystemName>\n"
//                + "            <CreationFlag>overwrite</CreationFlag>\n"
//                + "            <DeleteOnTermination>true</DeleteOnTermination>\n"
//                + "            <Target>\n"
//                + "                <URI>http://192.168.152.5:8080/storage/FileUploadServlet?path=http:__192.168.152.5:8080_wspgrade/10196/gemlca-1outt/Job0/outputs/10532510229060643zentest/0</URI>\n"
//                + "            </Target>\n"
//                + "        </DataStaging>\n"
//                + "        <DataStaging>\n"
//                + "            <FileName>guse.logg</FileName>\n"
//                + "            <FilesystemName>dcibridge.outputs.zip</FilesystemName>\n"
//                + "            <CreationFlag>overwrite</CreationFlag>\n"
//                + "            <DeleteOnTermination>true</DeleteOnTermination>\n"
//                + "            <Target>\n"
//                + "                <URI>http://192.168.152.5:8080/storage/FileUploadServlet?path=http:__192.168.152.5:8080_wspgrade/10196/gemlca-1outt/Job0/outputs/10532510229060643zentest/0</URI>\n"
//                + "            </Target>\n"
//                + "        </DataStaging>\n"
//                + "        <DataStaging>\n"
//                + "            <FileName>dcibridge.outputs.zip</FileName>\n"
//                + "            <CreationFlag>overwrite</CreationFlag>\n"
//                + "            <DeleteOnTermination>true</DeleteOnTermination>\n"
//                + "            <Target>\n"
//                + "                <URI>http://192.168.152.5:8080/storage/FileUploadServlet?path=http:__192.168.152.5:8080_wspgrade/10196/gemlca-1outt/Job0/outputs/10532510229060643zentest/0</URI>\n"
//                + "            </Target>\n"
//                + "        </DataStaging>\n"
//                + "    </JobDescription>\n"
//                + "    <ns4:SDL_Type xmlns:ns4=\"uri:MBSchedulingDescriptionLanguage\" xmlns:ns3=\"extension.dci\" xmlns:ns5=\"http://cloud.extension.jsdl\">\n"
//                + "        <ns4:Constraints>\n"
//                + "            <ns4:Middleware>\n"
//                + "                <ns4:DCIName>gemlca</ns4:DCIName>\n"
//                + "                <ns4:MyProxy/>\n"
//                + "                <ns4:ManagedResource>gemlca-resource.cpc.wmin.ac.uk:8443</ns4:ManagedResource>\n"
//                + "            </ns4:Middleware>\n"
//                + "            <ns4:Budget>0</ns4:Budget>\n"
//                + "        </ns4:Constraints>\n"
//                + "    </ns4:SDL_Type>\n"
//                + "    <ns3:extension_type xmlns:ns3=\"extension.dci\" xmlns:ns4=\"uri:MBSchedulingDescriptionLanguage\" xmlns:ns5=\"http://cloud.extension.jsdl\">\n"
//                + "        <ns3:wfiservice>http://192.168.152.5:8080/wfi/JobStatusService?wsdl</ns3:wfiservice>\n"
//                + "        <ns3:proxyservice>http://192.168.152.5:8080/wspgrade/CredentialProvider?wsdl</ns3:proxyservice>\n"
//                + "    </ns3:extension_type>\n"
//                + "</JobDefinition>";
//    }
//
//    public static String returnTestWorkflowTaverna2(String group,
//            String engineName, String name, String uuid) {
//        return "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n"
//                + "<JobDefinition xmlns=\"http://schemas.ggf.org/jsdl/2005/11/jsdl\" xmlns:ns2=\"http://schemas.ggf.org/jsdl/2005/11/jsdl-posix\" xmlns:ns3=\"uri:MBSchedulingDescriptionLanguage\" xmlns:ns4=\"extension.dci\" xmlns:ns5=\"http://cloud.extension.jsdl\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://schemas.ggf.org/jsdl/2005/11/jsdl\">\n"
//                + "    <JobDescription>\n"
//                + "        <JobIdentification>\n"
//                + "            <JobName>" + name + ":No description provided for this Legacy Code Grid Service</JobName>\n"
//                + "            <JobAnnotation>" + uuid + "</JobAnnotation>\n"
//                + "        </JobIdentification>\n"
//                + "        <Application clientip=\"161.74.11.130\">\n"
//                + "            <ApplicationName>guse://4399017697675086zentest/0/Job0/0</ApplicationName>\n"
//                + "            <ns2:POSIXApplication_Type>\n"
//                + "                <ns2:Argument>whatever</ns2:Argument>\n"
//                + "                <ns2:Argument>greeting</ns2:Argument>\n"
//                + "                <ns2:Output>stdout.log</ns2:Output>\n"
//                + "                <ns2:Error>stderr.log</ns2:Error>\n"
//                + "                <ns2:UserName>10196</ns2:UserName>\n"
//                + "                <ns2:GroupName>http://shiwa-portal2.cpc.wmin.ac.uk:8080/wspgrade</ns2:GroupName>\n"
//                + "            </ns2:POSIXApplication_Type>\n"
//                + "        </Application>\n"
//                + "        <Resources>\n"
//                + "            <CandidateHosts>\n"
//                + "                <HostName>" + name + ":No description provided for this Legacy Code Grid Service/" + engineName + "</HostName>\n"
//                + "            </CandidateHosts>\n"
//                + "            <OperatingSystem>\n"
//                + "                <OperatingSystemType>\n"
//                + "                    <OperatingSystemName>LINUX</OperatingSystemName>\n"
//                + "                </OperatingSystemType>\n"
//                + "            </OperatingSystem>\n"
//                + "        </Resources>\n"
//                + "        <DataStaging name=\"PORT0\">\n"
//                + "            <FileName>greeting</FileName>\n"
//                + "            <CreationFlag>overwrite</CreationFlag>\n"
//                + "            <DeleteOnTermination>true</DeleteOnTermination>\n"
//                + "            <Target>\n"
//                + "                <URI>http://shiwa-portal2.cpc.wmin.ac.uk:8080/storage/FileUploadServlet?path=" + group + "/13681/testWorkflowTaverna2/Job0/outputs/4399017697675086zentest/0/&amp;link=PORT0</URI>\n"
//                + "            </Target>\n"
//                + "        </DataStaging>\n"
//                + "        <DataStaging>\n"
//                + "            <FileName>stderr.log</FileName>\n"
//                + "            <CreationFlag>overwrite</CreationFlag>\n"
//                + "            <DeleteOnTermination>true</DeleteOnTermination>\n"
//                + "            <Target>\n"
//                + "                <URI>http://shiwa-portal2.cpc.wmin.ac.uk:8080/storage/FileUploadServlet?path=" + group + "/13681/testWorkflowTaverna2/Job0/outputs/4399017697675086zentest/0</URI>\n"
//                + "            </Target>\n"
//                + "        </DataStaging>\n"
//                + "        <DataStaging>\n"
//                + "            <FileName>stdout.log</FileName>\n"
//                + "            <CreationFlag>overwrite</CreationFlag>\n"
//                + "            <DeleteOnTermination>true</DeleteOnTermination>\n"
//                + "            <Target>\n"
//                + "                <URI>http://shiwa-portal2.cpc.wmin.ac.uk:8080/storage/FileUploadServlet?path=" + group + "/13681/testWorkflowTaverna2/Job0/outputs/4399017697675086zentest/0</URI>\n"
//                + "            </Target>\n"
//                + "        </DataStaging>\n"
//                + "        <DataStaging>\n"
//                + "            <FileName>gridnfo.log</FileName>\n"
//                + "            <CreationFlag>overwrite</CreationFlag>\n"
//                + "            <DeleteOnTermination>true</DeleteOnTermination>\n"
//                + "            <Target>\n"
//                + "                <URI>http://shiwa-portal2.cpc.wmin.ac.uk:8080/storage/FileUploadServlet?path=" + group + "/13681/testWorkflowTaverna2/Job0/outputs/4399017697675086zentest/0</URI>\n"
//                + "            </Target>\n"
//                + "        </DataStaging>\n"
//                + "        <DataStaging>\n"
//                + "            <FileName>guse.jsdl</FileName>\n"
//                + "            <CreationFlag>overwrite</CreationFlag>\n"
//                + "            <DeleteOnTermination>true</DeleteOnTermination>\n"
//                + "            <Target>\n"
//                + "                <URI>http://shiwa-portal2.cpc.wmin.ac.uk:8080/storage/FileUploadServlet?path=" + group + "/13681/testWorkflowTaverna2/Job0/outputs/4399017697675086zentest/0</URI>\n"
//                + "            </Target>\n"
//                + "        </DataStaging>\n"
//                + "        <DataStaging>\n"
//                + "            <FileName>guse.logg</FileName>\n"
//                + "            <CreationFlag>overwrite</CreationFlag>\n"
//                + "            <DeleteOnTermination>true</DeleteOnTermination>\n"
//                + "            <Target>\n"
//                + "                <URI>http://shiwa-portal2.cpc.wmin.ac.uk:8080/storage/FileUploadServlet?path=" + group + "/13681/testWorkflowTaverna2/Job0/outputs/4399017697675086zentest/0</URI>\n"
//                + "            </Target>\n"
//                + "        </DataStaging>\n"
//                + "    </JobDescription>\n"
//                + "    <ns3:SDL_Type>\n"
//                + "        <ns3:Constraints>\n"
//                + "            <ns3:Middleware>\n"
//                + "                <ns3:DCIName>gemlca</ns3:DCIName>\n"
//                + "                <ns3:MyProxy/>\n"
//                + "                <ns3:ManagedResource>gemlca-devel.cpc.wmin.ac.uk:8443</ns3:ManagedResource>\n"
//                + "            </ns3:Middleware>\n"
//                + "            <ns3:Budget>0</ns3:Budget>\n"
//                + "        </ns3:Constraints>\n"
//                + "    </ns3:SDL_Type>\n"
//                + "    <ns4:extension_type>\n"
//                + "        <ns4:wfiservice>http://shiwa-portal2.cpc.wmin.ac.uk:8080/wfi/JobStatusService?wsdl</ns4:wfiservice>\n"
//                + "        <ns4:proxyservice>http://shiwa-portal2.cpc.wmin.ac.uk:8080/wspgrade/CredentialProvider?wsdl</ns4:proxyservice>\n"
//                + "    </ns4:extension_type>\n"
//                + "</JobDefinition>";
//    }
//
//    public static String returnQRCode(String group, String engineName) {
//        return "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n"
//                + "<JobDefinition xmlns=\"http://schemas.ggf.org/jsdl/2005/11/jsdl\" xmlns:ns2=\"http://schemas.ggf.org/jsdl/2005/11/jsdl-posix\" xmlns:ns3=\"uri:MBSchedulingDescriptionLanguage\" xmlns:ns4=\"extension.dci\" xmlns:ns5=\"http://cloud.extension.jsdl\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://schemas.ggf.org/jsdl/2005/11/jsdl\">\n"
//                + "    <JobDescription>\n"
//                + "        <JobIdentification>\n"
//                + "            <JobName>QRCodeMatrixGenerator#1.0:No description provided for this Legacy Code Grid Service</JobName>\n"
//                + "            <JobAnnotation>aba1b128-9c25-473f-8351-94775a0691c7</JobAnnotation>\n"
//                + "        </JobIdentification>\n"
//                + "        <Application clientip=\"161.74.11.130\">\n"
//                + "            <ApplicationName>guse://3041628687366873zentest/0/Job0/0</ApplicationName>\n"
//                + "            <ns2:POSIXApplication_Type>\n"
//                + "                <ns2:Argument>url</ns2:Argument>\n"
//                + "                <ns2:Argument>qr_code</ns2:Argument>\n"
//                + "                <ns2:Argument>status_code</ns2:Argument>\n"
//                + "                <ns2:Output>stdout.log</ns2:Output>\n"
//                + "                <ns2:Error>stderr.log</ns2:Error>\n"
//                + "                <ns2:UserName>10196</ns2:UserName>\n"
//                + "                <ns2:GroupName>http://127.0.0.1:8080/wspgrade</ns2:GroupName>\n"
//                + "            </ns2:POSIXApplication_Type>\n"
//                + "        </Application>\n"
//                + "        <Resources>\n"
//                + "            <CandidateHosts>\n"
//                + "                <HostName>QRCodeMatrixGenerator#1.0:No description provided for this Legacy Code Grid Service/" + engineName + "</HostName>\n"
//                + "            </CandidateHosts>\n"
//                + "            <OperatingSystem>\n"
//                + "                <OperatingSystemType>\n"
//                + "                    <OperatingSystemName>LINUX</OperatingSystemName>\n"
//                + "                </OperatingSystemType>\n"
//                + "            </OperatingSystem>\n"
//                + "        </Resources>\n"
//                + "        <DataStaging>\n"
//                + "            <FileName>url</FileName>\n"
//                + "            <CreationFlag>overwrite</CreationFlag>\n"
//                + "            <DeleteOnTermination>true</DeleteOnTermination>\n"
//                + "            <Source>\n"
//                + "                <URI>Default</URI>\n"
//                + "            </Source>\n"
//                + "        </DataStaging>\n"
//                + "        <DataStaging name=\"PORT1\">\n"
//                + "            <FileName>qr_code</FileName>\n"
//                + "            <CreationFlag>overwrite</CreationFlag>\n"
//                + "            <DeleteOnTermination>true</DeleteOnTermination>\n"
//                + "            <Target>\n"
//                + "                <URI>http://shiwa-portal2.cpc.wmin.ac.uk:8080/storage/FileUploadServlet?path=" + group + "/10196/QRCodeMatrixGenerator/Job0/outputs/3041628687366873zentest/0/&amp;link=PORT1</URI>\n"
//                + "            </Target>\n"
//                + "        </DataStaging>\n"
//                + "        <DataStaging name=\"PORT2\">\n"
//                + "            <FileName>status_code</FileName>\n"
//                + "            <CreationFlag>overwrite</CreationFlag>\n"
//                + "            <DeleteOnTermination>true</DeleteOnTermination>\n"
//                + "            <Target>\n"
//                + "                <URI>http://shiwa-portal2.cpc.wmin.ac.uk:8080/storage/FileUploadServlet?path=" + group + "/10196/QRCodeMatrixGenerator/Job0/outputs/3041628687366873zentest/0/&amp;link=PORT2</URI>\n"
//                + "            </Target>\n"
//                + "        </DataStaging>\n"
//                + "        <DataStaging>\n"
//                + "            <FileName>stderr.log</FileName>\n"
//                + "            <CreationFlag>overwrite</CreationFlag>\n"
//                + "            <DeleteOnTermination>true</DeleteOnTermination>\n"
//                + "            <Target>\n"
//                + "                <URI>http://shiwa-portal2.cpc.wmin.ac.uk:8080/storage/FileUploadServlet?path=" + group + "/10196/QRCodeMatrixGenerator/Job0/outputs/3041628687366873zentest/0</URI>\n"
//                + "            </Target>\n"
//                + "        </DataStaging>\n"
//                + "        <DataStaging>\n"
//                + "            <FileName>stdout.log</FileName>\n"
//                + "            <CreationFlag>overwrite</CreationFlag>\n"
//                + "            <DeleteOnTermination>true</DeleteOnTermination>\n"
//                + "            <Target>\n"
//                + "                <URI>http://shiwa-portal2.cpc.wmin.ac.uk:8080/storage/FileUploadServlet?path=" + group + "/10196/QRCodeMatrixGenerator/Job0/outputs/3041628687366873zentest/0</URI>\n"
//                + "            </Target>\n"
//                + "        </DataStaging>\n"
//                + "        <DataStaging>\n"
//                + "            <FileName>gridnfo.log</FileName>\n"
//                + "            <CreationFlag>overwrite</CreationFlag>\n"
//                + "            <DeleteOnTermination>true</DeleteOnTermination>\n"
//                + "            <Target>\n"
//                + "                <URI>http://shiwa-portal2.cpc.wmin.ac.uk:8080/storage/FileUploadServlet?path=" + group + "/10196/QRCodeMatrixGenerator/Job0/outputs/3041628687366873zentest/0</URI>\n"
//                + "            </Target>\n"
//                + "        </DataStaging>\n"
//                + "        <DataStaging>\n"
//                + "            <FileName>guse.jsdl</FileName>\n"
//                + "            <CreationFlag>overwrite</CreationFlag>\n"
//                + "            <DeleteOnTermination>true</DeleteOnTermination>\n"
//                + "            <Target>\n"
//                + "                <URI>http://shiwa-portal2.cpc.wmin.ac.uk:8080/storage/FileUploadServlet?path=" + group + "/10196/QRCodeMatrixGenerator/Job0/outputs/3041628687366873zentest/0</URI>\n"
//                + "            </Target>\n"
//                + "        </DataStaging>\n"
//                + "        <DataStaging>\n"
//                + "            <FileName>guse.logg</FileName>\n"
//                + "            <CreationFlag>overwrite</CreationFlag>\n"
//                + "            <DeleteOnTermination>true</DeleteOnTermination>\n"
//                + "            <Target>\n"
//                + "                <URI>http://shiwa-portal2.cpc.wmin.ac.uk:8080/storage/FileUploadServlet?path=" + group + "/10196/QRCodeMatrixGenerator/Job0/outputs/3041628687366873zentest/0</URI>\n"
//                + "            </Target>\n"
//                + "        </DataStaging>\n"
//                + "    </JobDescription>\n"
//                + "    <ns3:SDL_Type>\n"
//                + "        <ns3:Constraints>\n"
//                + "            <ns3:Middleware>\n"
//                + "                <ns3:DCIName>gemlca</ns3:DCIName>\n"
//                + "                <ns3:MyProxy/>\n"
//                + "                <ns3:ManagedResource>gemlca-devel.cpc.wmin.ac.uk:8443</ns3:ManagedResource>\n"
//                + "            </ns3:Middleware>\n"
//                + "            <ns3:Budget>0</ns3:Budget>\n"
//                + "        </ns3:Constraints>\n"
//                + "    </ns3:SDL_Type>\n"
//                + "    <ns4:extension_type>\n"
//                + "        <ns4:wfiservice>http://shiwa-portal2.cpc.wmin.ac.uk:8080/wfi/JobStatusService?wsdl</ns4:wfiservice>\n"
//                + "        <ns4:proxyservice>http://shiwa-portal2.cpc.wmin.ac.uk:8080/wspgrade/CredentialProvider?wsdl</ns4:proxyservice>\n"
//                + "    </ns4:extension_type>\n"
//                + "</JobDefinition>";
//    }
//
//    public static String returnMoteur() {
//        return "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n"
//                + "<JobDefinition xmlns=\"http://schemas.ggf.org/jsdl/2005/11/jsdl\" xmlns:ns2=\"http://schemas.ggf.org/jsdl/2005/11/jsdl-posix\" xmlns:ns3=\"uri:MBSchedulingDescriptionLanguage\" xmlns:ns4=\"extension.dci\" xmlns:ns5=\"http://cloud.extension.jsdl\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://schemas.ggf.org/jsdl/2005/11/jsdl\">\n"
//                + "    <JobDescription>\n"
//                + "        <JobIdentification>\n"
//                + "            <JobName>Moteur-WF1:Workflow 1 via GIB</JobName>\n"
//                + "            <JobAnnotation>6c8747a1-5754-49e6-b622-f42ca68612c4</JobAnnotation>\n"
//                + "        </JobIdentification>\n"
//                + "        <Application>\n"
//                + "            <ApplicationName>guse://10194083703154636zentest/0/Moteur/0</ApplicationName>\n"
//                + "            <ns2:POSIXApplication_Type>\n"
//                + "                <ns2:Argument>moteur_dir-inputs.xml</ns2:Argument>\n"
//                + "                <ns2:Argument>default.zip</ns2:Argument>\n"
//                + "                <ns2:Argument>results.zip</ns2:Argument>\n"
//                + "                <ns2:Output>stdout.log</ns2:Output>\n"
//                + "                <ns2:Error>stderr.log</ns2:Error>\n"
//                + "                <ns2:UserName>11109</ns2:UserName>\n"
//                + "                <ns2:GroupName>http://shiwa-portal2.cpc.wmin.ac.uk:8080/wspgrade</ns2:GroupName>\n"
//                + "            </ns2:POSIXApplication_Type>\n"
//                + "        </Application>\n"
//                + "        <Resources>\n"
//                + "            <CandidateHosts>\n"
//                + "                <HostName>Moteur-WF1:Workflow 1 via GIB/ngs.wmin.ac.uk</HostName>\n"
//                + "            </CandidateHosts>\n"
//                + "            <OperatingSystem>\n"
//                + "                <OperatingSystemType>\n"
//                + "                    <OperatingSystemName>LINUX</OperatingSystemName>\n"
//                + "                </OperatingSystemType>\n"
//                + "            </OperatingSystem>\n"
//                + "        </Resources>\n"
//                + "        <DataStaging>\n"
//                + "            <FileName>default.zip</FileName>\n"
//                + "            <CreationFlag>overwrite</CreationFlag>\n"
//                + "            <DeleteOnTermination>true</DeleteOnTermination>\n"
//                + "            <Source>\n"
//                + "                <URI>Default</URI>\n"
//                + "            </Source>\n"
//                + "        </DataStaging>\n"
//                + "        <DataStaging>\n"
//                + "            <FileName>moteur_dir-inputs.xml</FileName>\n"
//                + "            <CreationFlag>overwrite</CreationFlag>\n"
//                + "            <DeleteOnTermination>true</DeleteOnTermination>\n"
//                + "            <Source>\n"
//                + "                <URI>Default</URI>\n"
//                + "            </Source>\n"
//                + "        </DataStaging>\n"
//                + "        <DataStaging name=\"PORT2\">\n"
//                + "            <FileName>results.zip</FileName>\n"
//                + "            <CreationFlag>overwrite</CreationFlag>\n"
//                + "            <DeleteOnTermination>true</DeleteOnTermination>\n"
//                + "            <Target>\n"
//                + "                <URI>http://shiwa-portal2.cpc.wmin.ac.uk:8080/storage/FileUploadServlet?path=http:__shiwa-portal2.cpc.wmin.ac.uk:8080_wspgrade/11109/TestingWorkflowsEngines/Moteur/outputs/10194083703154636zentest/0/&amp;link=PORT2</URI>\n"
//                + "            </Target>\n"
//                + "        </DataStaging>\n"
//                + "        <DataStaging>\n"
//                + "            <FileName>stderr.log</FileName>\n"
//                + "            <CreationFlag>overwrite</CreationFlag>\n"
//                + "            <DeleteOnTermination>true</DeleteOnTermination>\n"
//                + "            <Target>\n"
//                + "                <URI>http://shiwa-portal2.cpc.wmin.ac.uk:8080/storage/FileUploadServlet?path=http:__shiwa-portal2.cpc.wmin.ac.uk:8080_wspgrade/11109/TestingWorkflowsEngines/Moteur/outputs/10194083703154636zentest/0</URI>\n"
//                + "            </Target>\n"
//                + "        </DataStaging>\n"
//                + "        <DataStaging>\n"
//                + "            <FileName>stdout.log</FileName>\n"
//                + "            <CreationFlag>overwrite</CreationFlag>\n"
//                + "            <DeleteOnTermination>true</DeleteOnTermination>\n"
//                + "            <Target>\n"
//                + "                <URI>http://shiwa-portal2.cpc.wmin.ac.uk:8080/storage/FileUploadServlet?path=http:__shiwa-portal2.cpc.wmin.ac.uk:8080_wspgrade/11109/TestingWorkflowsEngines/Moteur/outputs/10194083703154636zentest/0</URI>\n"
//                + "            </Target>\n"
//                + "        </DataStaging>\n"
//                + "        <DataStaging>\n"
//                + "            <FileName>gridnfo.log</FileName>\n"
//                + "            <CreationFlag>overwrite</CreationFlag>\n"
//                + "            <DeleteOnTermination>true</DeleteOnTermination>\n"
//                + "            <Target>\n"
//                + "                <URI>http://shiwa-portal2.cpc.wmin.ac.uk:8080/storage/FileUploadServlet?path=http:__shiwa-portal2.cpc.wmin.ac.uk:8080_wspgrade/11109/TestingWorkflowsEngines/Moteur/outputs/10194083703154636zentest/0</URI>\n"
//                + "            </Target>\n"
//                + "        </DataStaging>\n"
//                + "        <DataStaging>\n"
//                + "            <FileName>guse.jsdl</FileName>\n"
//                + "            <CreationFlag>overwrite</CreationFlag>\n"
//                + "            <DeleteOnTermination>true</DeleteOnTermination>\n"
//                + "            <Target>\n"
//                + "                <URI>http://shiwa-portal2.cpc.wmin.ac.uk:8080/storage/FileUploadServlet?path=http:__shiwa-portal2.cpc.wmin.ac.uk:8080_wspgrade/11109/TestingWorkflowsEngines/Moteur/outputs/10194083703154636zentest/0</URI>\n"
//                + "            </Target>\n"
//                + "        </DataStaging>\n"
//                + "        <DataStaging>\n"
//                + "            <FileName>guse.logg</FileName>\n"
//                + "            <CreationFlag>overwrite</CreationFlag>\n"
//                + "            <DeleteOnTermination>true</DeleteOnTermination>\n"
//                + "            <Target>\n"
//                + "                <URI>http://shiwa-portal2.cpc.wmin.ac.uk:8080/storage/FileUploadServlet?path=http:__shiwa-portal2.cpc.wmin.ac.uk:8080_wspgrade/11109/TestingWorkflowsEngines/Moteur/outputs/10194083703154636zentest/0</URI>\n"
//                + "            </Target>\n"
//                + "        </DataStaging>\n"
//                + "    </JobDescription>\n"
//                + "    <ns3:SDL_Type>\n"
//                + "        <ns3:Constraints>\n"
//                + "            <ns3:Middleware>\n"
//                + "                <ns3:DCIName>gemlca</ns3:DCIName>\n"
//                + "                <ns3:MyProxy/>\n"
//                + "                <ns3:ManagedResource>gemlca-devel.cpc.wmin.ac.uk:8443</ns3:ManagedResource>\n"
//                + "            </ns3:Middleware>\n"
//                + "            <ns3:Budget>0</ns3:Budget>\n"
//                + "        </ns3:Constraints>\n"
//                + "    </ns3:SDL_Type>\n"
//                + "    <ns4:extension_type>\n"
//                + "        <ns4:wfiservice>http://shiwa-portal2.cpc.wmin.ac.uk:8080/wfi/JobStatusService?wsdl</ns4:wfiservice>\n"
//                + "        <ns4:proxyservice>http://shiwa-portal2.cpc.wmin.ac.uk:8080/wspgrade/CredentialProvider?wsdl</ns4:proxyservice>\n"
//                + "    </ns4:extension_type>\n"
//                + "</JobDefinition>\n";
//    }
//
//    public static String returnKepler() {
//        return "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n"
//                + "<JobDefinition xmlns=\"http://schemas.ggf.org/jsdl/2005/11/jsdl\" xmlns:ns2=\"http://schemas.ggf.org/jsdl/2005/11/jsdl-posix\" xmlns:ns3=\"uri:MBSchedulingDescriptionLanguage\" xmlns:ns4=\"extension.dci\" xmlns:ns5=\"http://cloud.extension.jsdl\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://schemas.ggf.org/jsdl/2005/11/jsdl\">\n"
//                + "    <JobDescription>\n"
//                + "        <JobIdentification>\n"
//                + "            <JobName>Kepler-WF2g:Workflow 2 via GIB</JobName>\n"
//                + "            <JobAnnotation>2fad523b-a71d-4a41-81ac-6ea420ac8d63</JobAnnotation>\n"
//                + "        </JobIdentification>\n"
//                + "        <Application>\n"
//                + "            <ApplicationName>guse://8973718327622532zentest/0/Job0/0</ApplicationName>\n"
//                + "            <ns2:POSIXApplication_Type>\n"
//                + "                <ns2:Argument>kepler_wf2_files.zip</ns2:Argument>\n"
//                + "                <ns2:Argument>results.zip</ns2:Argument>\n"
//                + "                <ns2:Output>stdout.log</ns2:Output>\n"
//                + "                <ns2:Error>stderr.log</ns2:Error>\n"
//                + "                <ns2:UserName>11109</ns2:UserName>\n"
//                + "                <ns2:GroupName>http://shiwa-portal2.cpc.wmin.ac.uk:8080/wspgrade</ns2:GroupName>\n"
//                + "            </ns2:POSIXApplication_Type>\n"
//                + "        </Application>\n"
//                + "        <Resources>\n"
//                + "            <CandidateHosts>\n"
//                + "                <HostName>Kepler-WF2g:Workflow 2 via GIB/ngs.wmin.ac.uk</HostName>\n"
//                + "            </CandidateHosts>\n"
//                + "            <OperatingSystem>\n"
//                + "                <OperatingSystemType>\n"
//                + "                    <OperatingSystemName>LINUX</OperatingSystemName>\n"
//                + "                </OperatingSystemType>\n"
//                + "            </OperatingSystem>\n"
//                + "        </Resources>\n"
//                + "        <DataStaging>\n"
//                + "            <FileName>kepler_wf2_files.zip</FileName>\n"
//                + "            <CreationFlag>overwrite</CreationFlag>\n"
//                + "            <DeleteOnTermination>true</DeleteOnTermination>\n"
//                + "            <Source>\n"
//                + "                <URI>Default</URI>\n"
//                + "            </Source>\n"
//                + "        </DataStaging>\n"
//                + "        <DataStaging name=\"PORT1\">\n"
//                + "            <FileName>results.zip</FileName>\n"
//                + "            <CreationFlag>overwrite</CreationFlag>\n"
//                + "            <DeleteOnTermination>true</DeleteOnTermination>\n"
//                + "            <Target>\n"
//                + "                <URI>http://shiwa-portal2.cpc.wmin.ac.uk:8080/storage/FileUploadServlet?path=http:__shiwa-portal2.cpc.wmin.ac.uk:8080_wspgrade/11109/1JobWF/Job0/outputs/8973718327622532zentest/0/&amp;link=PORT1</URI>\n"
//                + "            </Target>\n"
//                + "        </DataStaging>\n"
//                + "        <DataStaging>\n"
//                + "            <FileName>stderr.log</FileName>\n"
//                + "            <CreationFlag>overwrite</CreationFlag>\n"
//                + "            <DeleteOnTermination>true</DeleteOnTermination>\n"
//                + "            <Target>\n"
//                + "                <URI>http://shiwa-portal2.cpc.wmin.ac.uk:8080/storage/FileUploadServlet?path=http:__shiwa-portal2.cpc.wmin.ac.uk:8080_wspgrade/11109/1JobWF/Job0/outputs/8973718327622532zentest/0</URI>\n"
//                + "            </Target>\n"
//                + "        </DataStaging>\n"
//                + "        <DataStaging>\n"
//                + "            <FileName>stdout.log</FileName>\n"
//                + "            <CreationFlag>overwrite</CreationFlag>\n"
//                + "            <DeleteOnTermination>true</DeleteOnTermination>\n"
//                + "            <Target>\n"
//                + "                <URI>http://shiwa-portal2.cpc.wmin.ac.uk:8080/storage/FileUploadServlet?path=http:__shiwa-portal2.cpc.wmin.ac.uk:8080_wspgrade/11109/1JobWF/Job0/outputs/8973718327622532zentest/0</URI>\n"
//                + "            </Target>\n"
//                + "        </DataStaging>\n"
//                + "        <DataStaging>\n"
//                + "            <FileName>gridnfo.log</FileName>\n"
//                + "            <CreationFlag>overwrite</CreationFlag>\n"
//                + "            <DeleteOnTermination>true</DeleteOnTermination>\n"
//                + "            <Target>\n"
//                + "                <URI>http://shiwa-portal2.cpc.wmin.ac.uk:8080/storage/FileUploadServlet?path=http:__shiwa-portal2.cpc.wmin.ac.uk:8080_wspgrade/11109/1JobWF/Job0/outputs/8973718327622532zentest/0</URI>\n"
//                + "            </Target>\n"
//                + "        </DataStaging>\n"
//                + "        <DataStaging>\n"
//                + "            <FileName>guse.jsdl</FileName>\n"
//                + "            <CreationFlag>overwrite</CreationFlag>\n"
//                + "            <DeleteOnTermination>true</DeleteOnTermination>\n"
//                + "            <Target>\n"
//                + "                <URI>http://shiwa-portal2.cpc.wmin.ac.uk:8080/storage/FileUploadServlet?path=http:__shiwa-portal2.cpc.wmin.ac.uk:8080_wspgrade/11109/1JobWF/Job0/outputs/8973718327622532zentest/0</URI>\n"
//                + "            </Target>\n"
//                + "        </DataStaging>\n"
//                + "        <DataStaging>\n"
//                + "            <FileName>guse.logg</FileName>\n"
//                + "            <CreationFlag>overwrite</CreationFlag>\n"
//                + "            <DeleteOnTermination>true</DeleteOnTermination>\n"
//                + "            <Target>\n"
//                + "                <URI>http://shiwa-portal2.cpc.wmin.ac.uk:8080/storage/FileUploadServlet?path=http:__shiwa-portal2.cpc.wmin.ac.uk:8080_wspgrade/11109/1JobWF/Job0/outputs/8973718327622532zentest/0</URI>\n"
//                + "            </Target>\n"
//                + "        </DataStaging>\n"
//                + "    </JobDescription>\n"
//                + "    <ns3:SDL_Type>\n"
//                + "        <ns3:Constraints>\n"
//                + "            <ns3:Middleware>\n"
//                + "                <ns3:DCIName>gemlca</ns3:DCIName>\n"
//                + "                <ns3:MyProxy/>\n"
//                + "                <ns3:ManagedResource>gemlca-devel.cpc.wmin.ac.uk:8443</ns3:ManagedResource>\n"
//                + "            </ns3:Middleware>\n"
//                + "            <ns3:Budget>0</ns3:Budget>\n"
//                + "        </ns3:Constraints>\n"
//                + "    </ns3:SDL_Type>\n"
//                + "    <ns4:extension_type>\n"
//                + "        <ns4:wfiservice>http://shiwa-portal2.cpc.wmin.ac.uk:8080/wfi/JobStatusService?wsdl</ns4:wfiservice>\n"
//                + "        <ns4:proxyservice>http://shiwa-portal2.cpc.wmin.ac.uk:8080/wspgrade/CredentialProvider?wsdl</ns4:proxyservice>\n"
//                + "    </ns4:extension_type>\n"
//                + "</JobDefinition>\n";
//    }
//
//    public static String returnTriana() {
//        return "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n"
//                + "<JobDefinition xmlns=\"http://schemas.ggf.org/jsdl/2005/11/jsdl\" xmlns:ns2=\"http://schemas.ggf.org/jsdl/2005/11/jsdl-posix\" xmlns:ns3=\"uri:MBSchedulingDescriptionLanguage\" xmlns:ns4=\"extension.dci\" xmlns:ns5=\"http://cloud.extension.jsdl\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://schemas.ggf.org/jsdl/2005/11/jsdl\">\n"
//                + "    <JobDescription>\n"
//                + "        <JobIdentification>\n"
//                + "            <JobName>ImageMerger99-Triana-3.2.3-1.0:Triana Image Merger</JobName>\n"
//                + "            <JobAnnotation>6c067134-63ce-41cb-9eab-57629b02272b</JobAnnotation>\n"
//                + "        </JobIdentification>\n"
//                + "        <Application>\n"
//                + "            <ApplicationName>guse://9163684177024113zentest/0/Job0/0</ApplicationName>\n"
//                + "            <ns2:POSIXApplication_Type>\n"
//                + "                <ns2:Argument>01.gif</ns2:Argument>\n"
//                + "                <ns2:Argument>02.gif</ns2:Argument>\n"
//                + "                <ns2:Argument>03.gif</ns2:Argument>\n"
//                + "                <ns2:Argument>04.gif</ns2:Argument>\n"
//                + "                <ns2:Argument>05.gif</ns2:Argument>\n"
//                + "                <ns2:Argument>06.gif</ns2:Argument>\n"
//                + "                <ns2:Argument>res1.gif</ns2:Argument>\n"
//                + "                <ns2:Argument>res2.gif</ns2:Argument>\n"
//                + "                <ns2:Argument>res3.gif</ns2:Argument>\n"
//                + "                <ns2:Output>stdout.log</ns2:Output>\n"
//                + "                <ns2:Error>stderr.log</ns2:Error>\n"
//                + "                <ns2:UserName>11109</ns2:UserName>\n"
//                + "                <ns2:GroupName>http://shiwa-portal2.cpc.wmin.ac.uk:8080/wspgrade</ns2:GroupName>\n"
//                + "            </ns2:POSIXApplication_Type>\n"
//                + "        </Application>\n"
//                + "        <Resources>\n"
//                + "            <CandidateHosts>\n"
//                + "                <HostName>ImageMerger99-Triana-3.2.3-1.0:Triana Image Merger/ngs.wmin.ac.uk</HostName>\n"
//                + "            </CandidateHosts>\n"
//                + "            <OperatingSystem>\n"
//                + "                <OperatingSystemType>\n"
//                + "                    <OperatingSystemName>LINUX</OperatingSystemName>\n"
//                + "                </OperatingSystemType>\n"
//                + "            </OperatingSystem>\n"
//                + "        </Resources>\n"
//                + "        <DataStaging>\n"
//                + "            <FileName>02.gif</FileName>\n"
//                + "            <CreationFlag>overwrite</CreationFlag>\n"
//                + "            <DeleteOnTermination>true</DeleteOnTermination>\n"
//                + "            <Source>\n"
//                + "                <URI>Default</URI>\n"
//                + "            </Source>\n"
//                + "        </DataStaging>\n"
//                + "        <DataStaging>\n"
//                + "            <FileName>01.gif</FileName>\n"
//                + "            <CreationFlag>overwrite</CreationFlag>\n"
//                + "            <DeleteOnTermination>true</DeleteOnTermination>\n"
//                + "            <Source>\n"
//                + "                <URI>Default</URI>\n"
//                + "            </Source>\n"
//                + "        </DataStaging>\n"
//                + "        <DataStaging>\n"
//                + "            <FileName>06.gif</FileName>\n"
//                + "            <CreationFlag>overwrite</CreationFlag>\n"
//                + "            <DeleteOnTermination>true</DeleteOnTermination>\n"
//                + "            <Source>\n"
//                + "                <URI>Default</URI>\n"
//                + "            </Source>\n"
//                + "        </DataStaging>\n"
//                + "        <DataStaging>\n"
//                + "            <FileName>05.gif</FileName>\n"
//                + "            <CreationFlag>overwrite</CreationFlag>\n"
//                + "            <DeleteOnTermination>true</DeleteOnTermination>\n"
//                + "            <Source>\n"
//                + "                <URI>Default</URI>\n"
//                + "            </Source>\n"
//                + "        </DataStaging>\n"
//                + "        <DataStaging>\n"
//                + "            <FileName>04.gif</FileName>\n"
//                + "            <CreationFlag>overwrite</CreationFlag>\n"
//                + "            <DeleteOnTermination>true</DeleteOnTermination>\n"
//                + "            <Source>\n"
//                + "                <URI>Default</URI>\n"
//                + "            </Source>\n"
//                + "        </DataStaging>\n"
//                + "        <DataStaging>\n"
//                + "            <FileName>03.gif</FileName>\n"
//                + "            <CreationFlag>overwrite</CreationFlag>\n"
//                + "            <DeleteOnTermination>true</DeleteOnTermination>\n"
//                + "            <Source>\n"
//                + "                <URI>Default</URI>\n"
//                + "            </Source>\n"
//                + "        </DataStaging>\n"
//                + "        <DataStaging name=\"PORT8\">\n"
//                + "            <FileName>res3.gif</FileName>\n"
//                + "            <CreationFlag>overwrite</CreationFlag>\n"
//                + "            <DeleteOnTermination>true</DeleteOnTermination>\n"
//                + "            <Target>\n"
//                + "                <URI>http://shiwa-portal2.cpc.wmin.ac.uk:8080/storage/FileUploadServlet?path=http:__shiwa-portal2.cpc.wmin.ac.uk:8080_wspgrade/11109/ImageMerger/Job0/outputs/9163684177024113zentest/0/&amp;link=PORT8</URI>\n"
//                + "            </Target>\n"
//                + "        </DataStaging>\n"
//                + "        <DataStaging name=\"PORT7\">\n"
//                + "            <FileName>res2.gif</FileName>\n"
//                + "            <CreationFlag>overwrite</CreationFlag>\n"
//                + "            <DeleteOnTermination>true</DeleteOnTermination>\n"
//                + "            <Target>\n"
//                + "                <URI>http://shiwa-portal2.cpc.wmin.ac.uk:8080/storage/FileUploadServlet?path=http:__shiwa-portal2.cpc.wmin.ac.uk:8080_wspgrade/11109/ImageMerger/Job0/outputs/9163684177024113zentest/0/&amp;link=PORT7</URI>\n"
//                + "            </Target>\n"
//                + "        </DataStaging>\n"
//                + "        <DataStaging name=\"PORT6\">\n"
//                + "            <FileName>res1.gif</FileName>\n"
//                + "            <CreationFlag>overwrite</CreationFlag>\n"
//                + "            <DeleteOnTermination>true</DeleteOnTermination>\n"
//                + "            <Target>\n"
//                + "                <URI>http://shiwa-portal2.cpc.wmin.ac.uk:8080/storage/FileUploadServlet?path=http:__shiwa-portal2.cpc.wmin.ac.uk:8080_wspgrade/11109/ImageMerger/Job0/outputs/9163684177024113zentest/0/&amp;link=PORT6</URI>\n"
//                + "            </Target>\n"
//                + "        </DataStaging>\n"
//                + "        <DataStaging>\n"
//                + "            <FileName>stderr.log</FileName>\n"
//                + "            <CreationFlag>overwrite</CreationFlag>\n"
//                + "            <DeleteOnTermination>true</DeleteOnTermination>\n"
//                + "            <Target>\n"
//                + "                <URI>http://shiwa-portal2.cpc.wmin.ac.uk:8080/storage/FileUploadServlet?path=http:__shiwa-portal2.cpc.wmin.ac.uk:8080_wspgrade/11109/ImageMerger/Job0/outputs/9163684177024113zentest/0</URI>\n"
//                + "            </Target>\n"
//                + "        </DataStaging>\n"
//                + "        <DataStaging>\n"
//                + "            <FileName>stdout.log</FileName>\n"
//                + "            <CreationFlag>overwrite</CreationFlag>\n"
//                + "            <DeleteOnTermination>true</DeleteOnTermination>\n"
//                + "            <Target>\n"
//                + "                <URI>http://shiwa-portal2.cpc.wmin.ac.uk:8080/storage/FileUploadServlet?path=http:__shiwa-portal2.cpc.wmin.ac.uk:8080_wspgrade/11109/ImageMerger/Job0/outputs/9163684177024113zentest/0</URI>\n"
//                + "            </Target>\n"
//                + "        </DataStaging>\n"
//                + "        <DataStaging>\n"
//                + "            <FileName>gridnfo.log</FileName>\n"
//                + "            <CreationFlag>overwrite</CreationFlag>\n"
//                + "            <DeleteOnTermination>true</DeleteOnTermination>\n"
//                + "            <Target>\n"
//                + "                <URI>http://shiwa-portal2.cpc.wmin.ac.uk:8080/storage/FileUploadServlet?path=http:__shiwa-portal2.cpc.wmin.ac.uk:8080_wspgrade/11109/ImageMerger/Job0/outputs/9163684177024113zentest/0</URI>\n"
//                + "            </Target>\n"
//                + "        </DataStaging>\n"
//                + "        <DataStaging>\n"
//                + "            <FileName>guse.jsdl</FileName>\n"
//                + "            <CreationFlag>overwrite</CreationFlag>\n"
//                + "            <DeleteOnTermination>true</DeleteOnTermination>\n"
//                + "            <Target>\n"
//                + "                <URI>http://shiwa-portal2.cpc.wmin.ac.uk:8080/storage/FileUploadServlet?path=http:__shiwa-portal2.cpc.wmin.ac.uk:8080_wspgrade/11109/ImageMerger/Job0/outputs/9163684177024113zentest/0</URI>\n"
//                + "            </Target>\n"
//                + "        </DataStaging>\n"
//                + "        <DataStaging>\n"
//                + "            <FileName>guse.logg</FileName>\n"
//                + "            <CreationFlag>overwrite</CreationFlag>\n"
//                + "            <DeleteOnTermination>true</DeleteOnTermination>\n"
//                + "            <Target>\n"
//                + "                <URI>http://shiwa-portal2.cpc.wmin.ac.uk:8080/storage/FileUploadServlet?path=http:__shiwa-portal2.cpc.wmin.ac.uk:8080_wspgrade/11109/ImageMerger/Job0/outputs/9163684177024113zentest/0</URI>\n"
//                + "            </Target>\n"
//                + "        </DataStaging>\n"
//                + "    </JobDescription>\n"
//                + "    <ns3:SDL_Type>\n"
//                + "        <ns3:Constraints>\n"
//                + "            <ns3:Middleware>\n"
//                + "                <ns3:DCIName>gemlca</ns3:DCIName>\n"
//                + "                <ns3:MyProxy/>\n"
//                + "                <ns3:ManagedResource>gemlca-devel.cpc.wmin.ac.uk:8443</ns3:ManagedResource>\n"
//                + "            </ns3:Middleware>\n"
//                + "            <ns3:Budget>0</ns3:Budget>\n"
//                + "        </ns3:Constraints>\n"
//                + "    </ns3:SDL_Type>\n"
//                + "    <ns4:extension_type>\n"
//                + "        <ns4:wfiservice>http://shiwa-portal2.cpc.wmin.ac.uk:8080/wfi/JobStatusService?wsdl</ns4:wfiservice>\n"
//                + "        <ns4:proxyservice>http://shiwa-portal2.cpc.wmin.ac.uk:8080/wspgrade/CredentialProvider?wsdl</ns4:proxyservice>\n"
//                + "    </ns4:extension_type>\n"
//                + "</JobDefinition>\n";
//    }
//}
